version: "3.8"
networks:
  nesjs-network:
services:
  postgres:
    hostname: postgres
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./calories-app-backend/data:/data
    env_file:
      - docker.env
    networks:
      - nesjs-network
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    logging:
      driver: none
    networks:
      - nesjs-network
    environment:
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_LISTEN_PORT: 8080
    env_file:
      - pgadmin.env
    ports:
      - "5050:8080"
    links:
      - postgres
    volumes:
      - ./calories-app-backend/pgadmin:/pgadmin

  calories-app-backend:
    container_name: calories-app-backend
    build:
      context: ./calories-app-backend
      dockerfile: Dockerfile
    working_dir: /calories-app-backend
    ports:
      - "3000:3000"
      - "9229:9229"
    depends_on:
      - postgres
    networks:
      - nesjs-network
    volumes:
      - "./calories-app-backend:/calories-app-backend"
    command: >
      bash -c -e "
        npm install &&
        npm run start:dev"
